# Generated by Django 2.2.3 on 2019-09-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.CharField(default='尚未有公布的作业', max_length=12800, verbose_name='作业公告栏')),
            ],
        ),
    ]
