# Generated by Django 2.2.3 on 2019-10-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'HomeworkInf', 'verbose_name_plural': 'HomeworkInf'},
        ),
        migrations.RemoveField(
            model_name='homework',
            name='homework',
        ),
        migrations.AddField(
            model_name='homework',
            name='hw',
            field=models.TextField(default='尚未有公布的作业', verbose_name='作业公告栏'),
        ),
    ]
