# Generated by Django 2.2.3 on 2019-07-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('sex', models.IntegerField(choices=[(1, 'male'), (2, 'female'), (0, 'unknown')], verbose_name='sex')),
                ('profession', models.CharField(max_length=128, verbose_name='job')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('qq', models.CharField(max_length=128, verbose_name='qq')),
                ('phone', models.CharField(max_length=128, verbose_name='phone')),
                ('status', models.IntegerField(choices=[(0, 'applying'), (1, 'passed'), (2, 'refused')], default=0, verbose_name='checkStatus')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='createTime')),
            ],
            options={
                'verbose_name': 'StudentInf',
                'verbose_name_plural': 'StudentInf',
            },
        ),
    ]
