# Generated by Django 2.2.3 on 2019-09-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.CharField(default='尚未批改', max_length=128, verbose_name='成绩'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=128, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=128, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profession',
            field=models.CharField(max_length=128, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='qq',
            field=models.CharField(max_length=128, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female'), (0, 'unknown')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, 'applying'), (1, 'passed'), (2, 'refused')], default=0, verbose_name='状态'),
        ),
    ]
