# Generated by Django 2.2.3 on 2019-09-18 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='homework',
        ),
    ]
